Enable support for SSL by simply dropping an ssl.crt and an ssl.key in the directory.
This is helpful for running Weaver UI projects in a development environment with SSL.

When both the `ssl.crt` and the `ssl.key` files are missing, the service should automatically use the classic non-HTTPS mode.

Example SSL self-signed cert generation using openssl (with 40 days expiration):
```
openssl genrsa -out ssl.key 4096

openssl req -new -key ssl.key -out ssl.csr

openssl x509 -req -days 40 -in ssl.csr -signkey ssl.key -out ssl.crt
```

When using SSL, any socket URLs will need to be in SSL.
If you get an error like:
```
SecurityError: An insecure SockJS connection may not be initiated from a page loaded over HTTPS
```

Then you have a non-HTTPS URL somewhere in a configuration that is used for SockJS connections.
Change this to HTTPS.